import "./globals.css";
import{Manrope} from "next/font/google"

export const metadata = {
  title: "TICWAY- Tu Empresa de Informática y Tecnología en Vitoria ",
  description: "Generated by create next app",
};

const Manropefont = Manrope({
  subsets: ["latin"],
  weight: [ '200' ,'300' , '400' , '500' , '600' , '700'],
  display: "swap"
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link
  rel="stylesheet"
  type="text/css"
  charset="UTF-8"
  href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
/>
<link
  rel="stylesheet"
  type="text/css"
  href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
/>
      </head>
      <body className={Manropefont.className}>{children}</body>
    </html>
  );
}
